semantic-release:
  rules:
    - if: '$SEMANTIC_RELEASE && $CI_COMMIT_BRANCH == "main"'
  stage: release
  needs: []
  before_script:
    - apk update -q && apk add --no-cache -q git-lfs
    - npm install semantic-release@23.0.0 @semantic-release/changelog@6.0.3 @semantic-release/exec@6.0.3 @semantic-release/git@10.0.1 @semantic-release/gitlab@13.0.2 conventional-changelog-conventionalcommits@7.0.2 semantic-release-replace-plugin@1.2.7 -D
    - git lfs install
  script:
    - npx semantic-release
    - >
      if [ -e "build.env" ]; then
        echo "File exists at build.env"
      else
        echo "File does not exist at build.env"
        exit 255
      fi
  image: node:21.6.0-alpine3.19
  tags:
    - gitlab-org-docker
  allow_failure:
    exit_codes: # User defined exit code
      - 137
      - 255
  variables:
    GIT_BOT_HASH: 123ba649e66411db6837485119a23865
    GIT_AUTHOR_NAME: project_${CI_PROJECT_ID}_bot_${GIT_BOT_HASH}
    GIT_AUTHOR_EMAIL: project${CI_PROJECT_ID}_bot_${GIT_BOT_HASH}@noreply.${CI_SERVER_HOST}
    GIT_COMMITTER_NAME: project_${CI_PROJECT_ID}_bot_${GIT_BOT_HASH}
    GIT_COMMITTER_EMAIL: project${CI_PROJECT_ID}_bot_${GIT_BOT_HASH}@noreply.${CI_SERVER_HOST}
  artifacts:
    reports:
      dotenv: build.env
